#!/bin/sh

set -eu

ROOT_DIR=$(CDPATH= cd -- "$(dirname -- "$0")/.." && pwd)
PLAYGROUND_ICP_HOME=${PLAYGROUND_ICP_HOME:-"$ROOT_DIR/tmp/icp-home"}
PLAYGROUND_ICP_NETWORK_NAME=${PLAYGROUND_ICP_NETWORK_NAME:-local}
PLAYGROUND_TMP_DIR=${PLAYGROUND_TMP_DIR:-"$ROOT_DIR/tmp"}
PLAYGROUND_INDEXER_BASE_URL=${PLAYGROUND_INDEXER_BASE_URL:-"http://127.0.0.1:${PLAYGROUND_INDEXER_PORT:-6901}"}
PLAYGROUND_PUBLIC_RPC_URL=${PLAYGROUND_PUBLIC_RPC_URL:-"http://127.0.0.1:${LOCAL_EVM_PORT:-6905}"}
PLAYGROUND_RPC_GATEWAY_URL=${PLAYGROUND_RPC_GATEWAY_URL:-"http://127.0.0.1:${PLAYGROUND_RPC_GATEWAY_PORT:-6902}"}
LOCAL_EVM_DEPLOYMENT_FILE=${LOCAL_EVM_DEPLOYMENT_FILE:-"$PLAYGROUND_TMP_DIR/local-escrow-deployment.json"}

export PLAYGROUND_INDEXER_BASE_URL
export PLAYGROUND_PUBLIC_RPC_URL
export PLAYGROUND_RPC_GATEWAY_URL
export LOCAL_EVM_DEPLOYMENT_FILE
export PLAYGROUND_TMP_DIR
export ICP_HOME="$PLAYGROUND_ICP_HOME"

icp --project-root-override "$ROOT_DIR" network ping "$PLAYGROUND_ICP_NETWORK_NAME" >/dev/null

if [ "${PLAYGROUND_SPAWN_PAYMENT_E2E_SKIP_SMOKE:-0}" != "1" ]; then
  PLAYGROUND_INDEXER_BASE_URL="$PLAYGROUND_INDEXER_BASE_URL" \
  PLAYGROUND_PUBLIC_RPC_URL="$PLAYGROUND_PUBLIC_RPC_URL" \
  PLAYGROUND_RPC_GATEWAY_URL="$PLAYGROUND_RPC_GATEWAY_URL" \
  PLAYGROUND_SPAWN_PAYMENT_E2E_REQUIRE_SMOKE_OUTPUT=1 \
    sh "$ROOT_DIR/scripts/playground-smoke.sh"
fi

exec sh "$ROOT_DIR/scripts/with-repo-node.sh" node "$ROOT_DIR/scripts/spawn-payment-e2e.mjs"
